// datatrack-vue/src/views/Login.vue
<template>
  <div class="max-w-md mx-auto mt-10">
    <div class="text-center mb-6">
      <h1 class="text-3xl font-bold text-gray-800">DataTrack</h1>
      <p class="text-gray-600">Manage your records efficiently</p>
    </div>
    <h2 class="text-2xl font-bold mb-4 text-center">DataTrack - Login</h2>
    <form @submit.prevent="login" class="space-y-4">
      <input v-model="email" placeholder="Email" class="w-full border p-2 rounded" required />
      <input v-model="password" placeholder="Password" type="password" class="w-full border p-2 rounded" required />
      <button type="submit" class="w-full bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-600">Login</button>
    </form>
    <p class="mt-4 text-center">
      Don't have an account? <router-link to="/register" class="text-blue-600">Register</router-link>
    </p>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import axios from 'axios'

const router = useRouter()
const email = ref('')
const password = ref('')

const login = async () => {
  try {
    const res = await axios.post('http://localhost:5000/api/auth/login', { email: email.value, password: password.value })
    localStorage.setItem('token', res.data.token)
    router.push('/')
  } catch (err) {
    alert('Login failed')
  }
}
</script>

// datatrack-react/src/pages/Login.jsx
// src/pages/Login.jsx
import React, { useState } from 'react';
import axios from 'axios';
import Footer from '../components/Footer';

export default function Login({ setToken }) {
  const [isLogin, setIsLogin] = useState(true);
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [fullName, setFullName] = useState('');

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const endpoint = isLogin ? 'login' : 'register';
      const data = isLogin ? { email, password } : { fullName, email, password };
      const res = await axios.post(`http://localhost:5000/api/auth/${endpoint}`, data);
      if (res.data.token) {
        localStorage.setItem('token', res.data.token);
        setToken(res.data.token);
      }
    } catch (err) {
      alert(err.response?.data?.msg || 'Authentication failed');
    }
  };

  return (
    <div>
      <h2>DataTrack - {isLogin ? 'Login' : 'Register'}</h2>
      <form onSubmit={handleSubmit}>
        {!isLogin && (
          <input
            type="text"
            placeholder="Full Name"
            value={fullName}
            onChange={e => setFullName(e.target.value)}
            required
          />
        )}
        <input
          type="email"
          placeholder="Email"
          value={email}
          onChange={e => setEmail(e.target.value)}
          required
        />
        <input
          type="password"
          placeholder="Password"
          value={password}
          onChange={e => setPassword(e.target.value)}
          required
        />
        <button type="submit">{isLogin ? 'Login' : 'Register'}</button>
      </form>
      <p>
        {isLogin ? "Don't have an account?" : "Already have an account?"}
        <button onClick={() => setIsLogin(!isLogin)}>
          {isLogin ? 'Register' : 'Login'}
        </button>
      </p>
      <Footer />
    </div>
  );
}
