// datatrack-vue/src/components/RecordForm.vue
<template>
  <form class="grid grid-cols-1 md:grid-cols-4 gap-4" @submit.prevent="submit">
    <input v-model="form.title" placeholder="Title" class="border p-2 rounded" required />
    <input v-model="form.category" placeholder="Category" class="border p-2 rounded" />
    <input v-model.number="form.amount" placeholder="Amount" type="number" class="border p-2 rounded" />
    <input v-model="form.description" placeholder="Description" class="border p-2 rounded" />
    <button class="bg-blue-600 text-white px-4 py-2 rounded md:col-span-4">Add</button>
  </form>
</template>

<script setup>
import { reactive } from 'vue'
import axios from 'axios'

const emit = defineEmits(['created'])
const form = reactive({ title: '', category: '', description: '', amount: null })
const token = localStorage.getItem('token')
const api = axios.create({ baseURL: 'http://localhost:5000/api' })

async function submit() {
  await api.post('/records', form, { headers: { Authorization: `Bearer ${token}` } })
  Object.assign(form, { title: '', category: '', description: '', amount: null })
  emit('created')
}
</script>

// datatrack-react/src/components/RecordForm.jsx
import React, { useState } from 'react';
import axios from 'axios';

export default function RecordForm({ token, onRefresh }) {
  const [title, setTitle] = useState('');
  const [category, setCategory] = useState('');
  const [amount, setAmount] = useState('');
  const [description, setDescription] = useState('');

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      await axios.post('http://localhost:5000/api/records', {
        title,
        category,
        amount: parseFloat(amount),
        description
      }, {
        headers: { Authorization: `Bearer ${token}` }
      });
      setTitle('');
      setCategory('');
      setAmount('');
      setDescription('');
      onRefresh();
    } catch (err) {
      alert('Failed to add record');
    }
  };

  return (
    <div>
      <h3>Add Record</h3>
      <form onSubmit={handleSubmit}>
        <input
          type="text"
          placeholder="Title"
          value={title}
          onChange={e => setTitle(e.target.value)}
          required
        />
        <input
          type="text"
          placeholder="Category"
          value={category}
          onChange={e => setCategory(e.target.value)}
        />
        <input
          type="number"
          placeholder="Amount"
          value={amount}
          onChange={e => setAmount(e.target.value)}
          step="0.01"
        />
        <textarea
          placeholder="Description"
          value={description}
          onChange={e => setDescription(e.target.value)}
        />
        <button type="submit">Add Record</button>
      </form>
    </div>
  );
}
